<h1><b>Statistique en Bioinformatique : </b> TME2 </h1>
<br>
L’objectif de ce TME est: 
<br>
<ul>
<li> objectif 1: comprendre les différences d'alignement global et local, </li>
<li> objectif 2: reconstruire une matrice de substitution du type Blosum, </li>
</ul>
<br>
<div class="alert alert-warning" role="alert" style="margin: 10px">
<p>**Soumission**</p>
<ul>
<li>Renomer le fichier TME1.ipynb pour TME2_NomEtudiant1_NomEtudiant2.ipynb </li>
<li>Soumettre à https://www.dropbox.com/request/ZylCDDpggbrN5toTiJKV </li>
</ul>
</div>
</div>

Nom etudiant 1 : Leroy Adrien
<br>
Nom etudiant 2 : Dorval Loïc
<br>

<b> Exercice 1 </b>: On va étudier un alignement “difficile” entre la protéine emph50s ribosomal L20 chez A. aeolicus, 
et la protéine ligase UBR5 chez l’homme (L’alignement structural est montré ci-dessous). 
<br>

<img src="bacthum.png" alt="Smiley face" height="210" width="202"> 



<br><br>
<b>A.</b> Récupérez la séquence de la protéine “E3 ubiquitin ligase UBR5” chez l’homme et de la protéine “50S ribosomal L20” chez A. aeolicus 
via le site <a href="http://www.uniprot.org/">Uniprot</a>  au format .fasta.

<br>
<b>B.</b> A l’aide du site <a href="https://www.ebi.ac.uk/Tools/psa/">psa</a>, alignez ces séquences. Commentez les faibles pourcentage d’identité malgré le bon alignement des ces structures.


Réponse : %Identity:      29/2826 ( 1.0%)
          On obtient ce résultat avec une différence de longueur de séquence

<b>C.</b> Récupérez la séquence de la protéine “metL Bifunctional aspartokinase/homoserine dehydrogenase 2” et de la protéine “lysC Lysine-sensitive aspartokinase 3” chez E. coli via le site <a href="http://www.uniprot.org/"> Uniprot </a> au format .fasta. Reproduisez, à l’aide du site <a href="https://www.ebi.ac.uk/Tools/psa/"> psa</a>, l’alignement global et local vu en TD. Observez la modification des résultats en changeant la matrice de substitution et/ou les pénalités de gap (“Gap_penalty” et “Extend_penalty”).

Reponse:en changeant l'ouverture de gap et l'extension de gap on fait varié les scores d'indentité et les scores de similarité.

<b>Exercice 2</b>: Score alignement global, local <br>
Faire une fonction pour calculer : 1) la pourcentage de identité, 2) la pourcentage de similarité, 3) le score d’un alignement en utilisant la matrix blosum62. Le calcul de la similarité doit prendre en considération les acides amine ayant la même propriété physico chimique. Dans notre cas, tous les acides amine qui ont des valeurs supérieur à zéro dans la matrice BLOSUM62. Le score basé sur la matrice blosum doit aussi prendre en considération les deux pénalités de gaps, ouverture et extension. Teste vos fonctions en utilisant le fichier test.fasta


In [1]:
import numpy as np

#variable initiation
aa = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'X']

#parameters
q = 21
gap_open = -5
gap_ext = 0.5

#files
input_test_f = 'test.fasta'
input_blosum_f = 'BLOSUM62.txt'

#For a simple test use:
input_test_f = 'testToy.fasta'



In [2]:
#Read the test.fasta file
def read_fasta(fichier):
    Liste_esp=[]
    Liste_seq=[]
    flux=open(fichier,'r')
    ligne=flux.readline()
    while ligne!='':
        ligne=ligne[0:-1]
        if ligne[0]=='>':
            Liste_esp.append(ligne)
        else:
            
            Liste_seq.append(ligne)
        ligne=flux.readline()
    return Liste_seq
    
testAln = read_fasta(input_test_f)
print (testAln)

['ACCD', 'A-CD']


In [11]:
#read Blosum
def read_blosum (input_f):
    flux=open(input_f,'r')
    ligne=flux.readline()
    mat=[]
    while ligne != '':
        ligne=ligne[0:-1]
        if ligne[0]=='#' or ligne[0]==' ':
            ligne=flux.readline()
        else:
            ligne=ligne[1:-1].split()
            mat.append(ligne[0:-1])
            ligne=flux.readline()
    mat=np.array(mat)
    mat=mat.astype(int)
    
    return mat[0:-1]
    
matr_62 = read_blosum (input_blosum_f)
print ('matrice Blosum :\n',matr_62)
print(np.shape(matr_62))

matrice Blosum :
 [[ 4 -1 -2 -2  0 -1 -1  0 -2 -1 -1 -1 -1 -2 -1  1  0 -3 -2  0 -2 -1  0]
 [-1  5  0 -2 -3  1  0 -2  0 -3 -2  2 -1 -3 -2 -1 -1 -3 -2 -3 -1  0 -1]
 [-2  0  6  1 -3  0  0  0  1 -3 -3  0 -2 -3 -2  1  0 -4 -2 -3  3  0 -1]
 [-2 -2  1  6 -3  0  2 -1 -1 -3 -4 -1 -3 -3 -1  0 -1 -4 -3 -3  4  1 -1]
 [ 0 -3 -3 -3  9 -3 -4 -3 -3 -1 -1 -3 -1 -2 -3 -1 -1 -2 -2 -1 -3 -3 -2]
 [-1  1  0  0 -3  5  2 -2  0 -3 -2  1  0 -3 -1  0 -1 -2 -1 -2  0  3 -1]
 [-1  0  0  2 -4  2  5 -2  0 -3 -3  1 -2 -3 -1  0 -1 -3 -2 -2  1  4 -1]
 [ 0 -2  0 -1 -3 -2 -2  6 -2 -4 -4 -2 -3 -3 -2  0 -2 -2 -3 -3 -1 -2 -1]
 [-2  0  1 -1 -3  0  0 -2  8 -3 -3 -1 -2 -1 -2 -1 -2 -2  2 -3  0  0 -1]
 [-1 -3 -3 -3 -1 -3 -3 -4 -3  4  2 -3  1  0 -3 -2 -1 -3 -1  3 -3 -3 -1]
 [-1 -2 -3 -4 -1 -2 -3 -4 -3  2  4 -2  2  0 -3 -2 -1 -2 -1  1 -4 -3 -1]
 [-1  2  0 -1 -3  1  1 -2 -1 -3 -2  5 -1 -3 -1  0 -1 -3 -2 -2  0  1 -1]
 [-1 -1 -2 -3 -1  0 -2 -3 -2  1  2 -1  5  0 -2 -1 -1 -1 -1  1 -3 -1 -1]
 [-2 -3 -3 -3 -2 -3 -3 -3 -1  0  0 -3  0  6 -4

In [38]:
def indentite_calcul(seq1, seq2, gap_open, gap_ext, matr_62, alphabet):
    Similarite=0
    Identite=0
    Score=0
    for i in range(len(seq1)):
        
        if seq1[i]!='-' and seq2[i]!='-': # si pas de gap
            Score+=matr_62[alphabet.index(seq1[i])][alphabet.index(seq2[i])]
            if matr_62[alphabet.index(seq1[i])][alphabet.index(seq2[i])]>=0: #similarité
                Similarite+=1
            if (seq1[i]==seq2[i]): #identité 
                Identite+=1
        else:
            if seq1[i]=='-': #cas gap sur seq 1
                if i>0 and seq1[i-1]=='-':
                    Score+=gap_ext
                else:
                    Score+=gap_open
                    
            if seq2[i]=='-': #cas gap sur seq 2
                if i>0 and seq2[i-1]=='-':
                    Score+=gap_ext
                else:
                    Score+=gap_open
                    
    Similarite/=len(seq1) 
    Identite/=len(seq1)
    return Identite, Similarite, Score

identitee,similarity,score = indentite_calcul(testAln[0], testAln[1], gap_open, gap_ext, matr_62,aa)
print ("identitee= ", identitee , "| similarity= ", similarity, "| score= ", score )

identitee=  0.75 | similarity=  0.75 | score=  10


<b>Exercice 3</b>: Matrice de substitution <br>
Faire une programme (plusieurs fonctions seront nécessaires) pour produire une matrix de substitution comme Blosum. Utiliser l’alignement du fichiers <b>blocks.dat</b>. 


In [39]:
from itertools import combinations, combinations_with_replacement
from collections import Counter


input_block_f = 'block.dat'

#For a simple test do:
input_block_f_toy = 'blockToy.dat'
#q = 3
aa_toy = ['A', 'B', 'C']

#generate all aa combination
aa.sort()
pairs_freq_dict = {x:0 for x in combinations_with_replacement(aa,2)}





In [40]:
#read alignment file
from io import StringIO 
import sys

def readAlnFile(input_f):
    flux=open(input_f)
    ligne=flux.readline()
    Aln=[]
    i=0
    while ligne != '':  #on lit jusqu'à la fin du fichier
        temp=[]
        Aln.append(temp)          #on ajoute une liste vide à chaque occurence 
        if ligne[-1]=='\n':       #on enlève le \n si présent au bout de la ligne 
            ligne=ligne[0:-1]
        for j in range(len(ligne)):  #on y ajoute chaque élement de la ligne dans cette liste
            Aln[i].append(ligne[j])
        ligne=flux.readline()     #on passe à la ligne d'après
        i+=1
    return np.array(Aln)          #on retourne la liste de liste sous la forme np.array


Aln=readAlnFile(input_block_f_toy)
print(Aln)

[['A' 'B' 'C' 'C' 'B']
 ['A' 'C' 'A' 'B' 'A']
 ['C' 'B' 'C' 'C' 'B']
 ['A' 'C' 'B' 'B' 'B']]


In [41]:
#compute fij frequences
import pandas as pd
import math

def combine (n,p):  #On fait une fonction uniquement pour la combinatoire
    X=math.factorial(n)/(math.factorial(n-p)*math.factorial(p))
    return X

def compute_Fij(Aln,alphabet):
    df=pd.DataFrame(np.zeros((len(alphabet),len(alphabet))),index=alphabet,columns=alphabet)
    for k in range(len(Aln[0])):
        liste_int=Aln[:,k]                                             #c'est la colonne pour la position k de chaque séquence
        liste_unique,counts=np.unique(liste_int,return_counts=True)    #on sort la liste les et le compte de chacun de ses membres
        for i in range(len(liste_unique)):
            for j in range(i,len(liste_unique)):
                if i==j:
                    if counts[i]>=2:                                   #Si c'est inférieur à 2 le résultat doit être nul
                        df[liste_unique[i]][liste_unique[j]]+=combine(counts[i],2)
                else:
                    df[liste_unique[i]][liste_unique[j]]+=counts[i]*counts[j]
    return df
######## Test ########
Fij=compute_Fij(Aln,aa_toy)
print(Fij,"\nMatrice des fréquences Fij\n",)



     A     B    C
A  3.0   0.0  0.0
B  4.0   5.0  0.0
C  5.0  10.0  3.0 
Matrice des fréquences Fij



In [42]:
#compute T
def compute_T(df):                 #on obtient T en faisant la somme total de toutes les colonnes 
    return np.sum(np.sum(df))      #et de toutes les lignes

######## Test ########
T=compute_T(Fij)
print("somme T :",T)

somme T : 30.0


In [43]:
#compute pi
def compute_Pi(df,T):                                    #calculer Pi revient à sommer la colonne et la ligne 
    return (df/(2*T)).sum(axis=0)+(df/(2*T)).sum(axis=1) #d'indice i de la matrice Fij/2T vu que qii/2 sera compter
                                                         #2 fois donc on retrouve la formule du TD
######## Test ########
Pi=compute_Pi(Fij,T)
print("liste des Pi : \n")
print(Pi)

liste des Pi : 

A    0.25
B    0.40
C    0.35
dtype: float64


In [44]:
#compute Sij
def compute_Sij(file):   
    #On rappelle toute nos fonction
    Aln=readAlnFile(file)
    alphabet=np.unique(Aln)    #on extrait l'alphabet depuis la matrice d'alignement
    alphabet.sort()            #on le range pour toujours avoir une matrice identique dans un ordre logique (alphabétique)
    df=compute_Fij(Aln,alphabet)
    T=compute_T(df)
    P=compute_Pi(df,T)
    S=pd.DataFrame(np.zeros((len(df.index),len(df.index))),index=df.index,columns=df.index)
    for i in S.index:
        for j in S.index:
            if j>=i:                                                      #on lit que la partie non nul de la matrice
                if i==j:
                    S[i][j]=math.log2((df[i][j]/T)/(P[i]**2))             #on remplit la diagonale 
                else:
                    S[j][i]=S[i][j]=math.log2((df[i][j]/T)/(P[i]*P[j]*2)) #on remplit simultanément la partie supérieur
    return S                                                              #et inférieur de la matrice (miroir)

######## Test ########
S_toy=compute_Sij(input_block_f_toy)
S=compute_Sij(input_block_f)


In [45]:
#print Matrix
print("matrice de substitution sur les données du TD :")
print(S_toy,"\n")
print("matrice de substitution sur les données du block.dat:")
print(S)

matrice de substitution sur les données du TD :
          A         B         C
A  0.678072 -0.584963 -0.070389
B -0.584963  0.058894  0.251539
C -0.070389  0.251539 -0.292782 

matrice de substitution sur les données du block.dat:
          A         C         D         E         F         G         H  \
A  1.412787  0.837937 -1.388499 -0.756938 -1.183122 -0.496285 -0.455525   
C  0.837937  3.199617 -3.206436 -2.976546  1.734936 -1.281577 -0.533737   
D -1.388499 -3.206436  3.203186  0.921453 -2.431022 -2.768367  0.102164   
E -0.756938 -2.976546  0.921453  2.356454 -1.164802 -2.871004  1.378560   
F -1.183122  1.734936 -2.431022 -1.164802  2.867416 -1.463836  0.964796   
G -0.496285 -1.281577 -2.768367 -2.871004 -1.463836  2.093620 -2.119040   
H -0.455525 -0.533737  0.102164  1.378560  0.964796 -2.119040  2.083499   
I -1.059804 -1.728069 -1.963469 -1.489948 -0.687422 -1.284775 -0.604315   
K -0.801010 -2.906861 -0.651320  0.614567 -0.882305 -2.143753 -0.453616   
L -0.594429 -0.156